/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temperatureconverter;

/**
 *
 * @author dvandenberge
 */
public class MainWindow extends javax.swing.JPanel {
    
    private CelsiusConverterService ccs;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.ccs=new CelsiusConverterService();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionLabel = new javax.swing.JLabel();
        temperatureEntry = new javax.swing.JTextField();
        celsiusConversionButton = new javax.swing.JButton();
        fahrenheitConversionButton = new javax.swing.JButton();
        temperatureDisplayLabel = new javax.swing.JLabel();
        temperatureOutputLabel = new javax.swing.JLabel();

        instructionLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        instructionLabel.setText("Enter Temperature to be converted:");

        celsiusConversionButton.setBackground(new java.awt.Color(255, 0, 0));
        celsiusConversionButton.setText("Convert to Celsius");
        celsiusConversionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celsiusConversionButtonActionPerformed(evt);
            }
        });

        fahrenheitConversionButton.setBackground(new java.awt.Color(0, 0, 255));
        fahrenheitConversionButton.setText("Convert to Fahrenheit");

        temperatureDisplayLabel.setText("Temperature:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fahrenheitConversionButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(celsiusConversionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(temperatureEntry))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(temperatureDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(temperatureOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(instructionLabel))
                .addGap(61, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(instructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperatureEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celsiusConversionButton)
                    .addComponent(temperatureOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fahrenheitConversionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void celsiusConversionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celsiusConversionButtonActionPerformed
        double temp=Double.parseDouble(temperatureEntry.getText());
        temperatureOutputLabel.setText(Double.toString(ccs.convertToCelsius(temp)));
    }//GEN-LAST:event_celsiusConversionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton celsiusConversionButton;
    private javax.swing.JButton fahrenheitConversionButton;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JLabel temperatureDisplayLabel;
    private javax.swing.JTextField temperatureEntry;
    private javax.swing.JLabel temperatureOutputLabel;
    // End of variables declaration//GEN-END:variables
}
